### ISSUE TITLE
Broken Examples

### ISSUE THREAD

**Issue by pmacMaps** [Esri/esri-leaflet-doc#229]
The purpose of this issue is to have a single reference point for the currently broken examples. 

Pages with services behind tokens. Need to update sample services:
- ~~https://esri.github.io/esri-leaflet/examples/querying-feature-layers-1.html~~
- ~~https://esri.github.io/esri-leaflet/examples/querying-feature-layers-2.html~~
- ~~https://esri.github.io/esri-leaflet/examples/spatial-queries.html~~
- ~~https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-1.html~~
- ~~https://esri.github.io/esri-leaflet/examples/labeling-features.html~~
- ~~https://esri.github.io/esri-leaflet/examples/layer-ordering.html~~
- ~~https://esri.github.io/esri-leaflet/examples/cedar-chart.html~~
- ~~https://esri.github.io/esri-leaflet/examples/dynamic-chart.html~~
- ~~https://esri.github.io/esri-leaflet/examples/styling-heatmaps.html~~
- ~~https://esri.github.io/esri-leaflet/examples/visualizing-time-with-feature-layer.html~~
- ~~https://esri.github.io/esri-leaflet/examples/styling-clusters.html~~
- ~~https://esri.github.io/esri-leaflet/examples/feature-layer-snapshot.html~~
- ~~https://esri.github.io/esri-leaflet/examples/renderers-plugin.html~~
- ~~https://esri.github.io/esri-leaflet/examples/editable.html~~

Not sure if it's working as expected:
- ~~https://esri.github.io/esri-leaflet/examples/zooming-to-all-features-2.html~~
- ~~https://esri.github.io/esri-leaflet/examples/webmap.html?id=13750b8b548d48bfa99a9731f2a93ba0~~
  * `9m84-ahhb - Firearm Assaults Map 2015` is being loaded using http instead of https
  * `Firearm Assaults Median Income` is being loaded using http instead of https

**Comment by pmacMaps** [comment]
@jgravois, I saw the webmap referenced above is owned by you.  Could you update the layers so that they use https instead of http?  I think that will resolve the issue with https://esri.github.io/esri-leaflet/examples/webmap.html?id=13750b8b548d48bfa99a9731f2a93ba0.

**Comment by jgravois** [comment]
I would, but  http://koop.dc.esri.com/socrata/seattle/9m84-ahhb/FeatureServer/0 is a Koop service that doesn't support SSL. probably best for one of y'all to author a new webmap.

**Comment by jwasilgeo** [comment]
Happy to help update the sample for <https://esri.github.io/esri-leaflet/examples/dynamic-chart.html> which I was originally involved in.

At the time of writing that sample page I recycled the [Portland Heritage Trees layer](https://services.arcgis.com/rOo16HdIMeOBI4Mb/arcgis/rest/services/Heritage_Trees_Portland/FeatureServer/0/).  Does anyone have a preference on a good alternative with a couple interesting attributes to chart?

**Comment by gavinr** [comment]
@jwasilgeo I found this service url https://www.portlandmaps.com/arcgis/rest/services/Public/Parks_Misc/MapServer/21/ via https://www.portlandoregon.gov/parks/41049 ... I think it's the same dataset - can you try swapping out the URLs and see if it works as expected?

**Comment by jwasilgeo** [comment]
That's a perfect substitute, thanks for finding that @gavinr.  I'm making the changes now.

**Comment by gavinr** [comment]
charts samples (#239 thanks @jwasilgeo!) and webmap samples are now fixed! getting close ...

**Comment by jwasilgeo** [comment]
For the still broken samples listed above that use a pdx neighborhoods layer, this could potentially be a replacement. Not 100% sure though.
https://www.portlandmaps.com/arcgis/rest/services/Public/Zoning/MapServer/32

**Comment by jwasilgeo** [comment]
layer ordering and spatial queries sample pages fixed (PR #240, thanks @pmacMaps)

**Comment by pmacMaps** [comment]
It looks like the broken [editable sample](https://esri.github.io/esri-leaflet/examples/editable.html) needs a polygon feature service.  I can create this service, but perhaps it makes more sense for an Esri staffer to create this service?

**Comment by gavinr** [comment]
here is an editable polygon layer on sampleserver6 - would this work maybe?

https://sampleserver6.arcgisonline.com/arcgis/rest/services/Military/FeatureServer/9

**Comment by gavinr** [comment]
Editing example now working (#242). Any other examples not working or are we good on this issue?

**Comment by pmacMaps** [comment]
I think we can close this issue.

**Comment by gavinr** [comment]
🎉 Thanks for all your contributions @pmacMaps!
